[workspace]

members = [
    "medic-check-rust",
    "medic-step-rust",
]
resolver = "1"

[workspace.dependencies]
clap = { version = "4.1.8" }
indoc = "2.0.1"
itertools = "0.12"
medic-lib = "0.1"
regex = "1.7"
