[doctor]
checks = [
  { check = "homebrew" },
  { check = "tool-versions", command = "plugin-installed", args = { plugin = "rust" } },
  { check = "tool-versions", command = "package-installed", args = { plugin = "rust" } },
  { name = "compile", shell = "cargo build --workspace" },
  { check = "rust", command = "crate-installed", args = { name = "cargo-audit" } },
  { check = "rust", command = "crate-installed", args = { name = "cargo-outdated" } },
  { check = "rust", command = "target-installed", args = { target = "aarch64-apple-darwin" } },
  { check = "rust", command = "target-installed", args = { target = "x86_64-apple-darwin" } },
]

[test]
checks = [
  { name = "Check for warnings", shell = "cargo build --workspace --features strict --color always", verbose = true },
  { step = "rust", command = "test", verbose = true },
]

[audit]
checks = [
  ## allow failure: chrono and time have known potential segfaults
  { name = "Audit crates", shell = "cargo audit --color always", allow_failure = true, verbose = true },
  { check = "rust", command = "format-check" },
  { step = "rust", command = "clippy" },
  { name = "Check md format", shell = "bin/dev/format-md --check", remedy = "bin/dev/format-md --all" },
]

[outdated]
checks = [
  { check = "rust", cd = "medic-check-rust" },
  { check = "rust", cd = "medic-outdated-rust" },
  { check = "rust", cd = "medic-step-rust" },
]

[update]
steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[shipit]
steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  { name = "Release", shell = "bin/dev/release", inline = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]
